# Generated by Django 3.0.3 on 2020-03-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('licence_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'unique_together': {('licence_id', 'name')},
            },
        ),
    ]
